### ISSUE TITLE
Update project to later .NET

### ISSUE THREAD

**Issue by mwedmark** [NefMoto/NefMotoOpenSource#19]
I started with jumping to 4.8 but the end result is aiming for .NET 7 (laetst released) whcih also will make this work in Linux/Mac/Windows.

**Comment by ljscodex** [comment]
you have this version working on net8 https://github.com/ljscodex/NefMotoOpenSource

**Comment by mwedmark** [comment]
Sorry no. Currently I'm in the middle of moving but I really never got to try this with the real ecu/cable. I'm not sure anyone has.  But if the .net 7 version is working .net 8 should be possible
